const types = {
    RESET: 'RESET',
    // mnemonic types
    ADD_WORD: "ADD_WORD",
    REMOVE_WORD: "REMOVE_WORD",

    // ethersjs calls
    RECOVER_WALLET_START: "RECOVER_WALLET_START",
    RECOVER_WALLET_ERROR: "RECOVER_WALLET_ERROR",
    RECOVER_WALLET_SUCCESS: "RECOVER_WALLET_SUCCESS",
    FETCH_BALANCE_START: "FETCH_BALANCE_START",
    FETCH_BALANCE_ERROR: "FETCH_BALANCE_ERROR",
    FETCH_BALANCE_SUCCESS: "FETCH_BALANCE_SUCCESS",
}

export default types